version: '3'

services:
  app:
    build: .
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIMER: 2000
